apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloapp
      version: green
  template:
    metadata:
      name: helloapp-pod
      labels:
        app: helloapp
        version: green
    spec:
      containers:
      - name: helloapp-container
        image: niranjankolli/eks-demo-lab:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: helloapp-svc
  labels:
    app: helloapp
spec:
  selector:
    app: helloapp
    version: green
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
